### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by dmc31a42** [dmc31a42/UnityL10nTool#6]
- [ ] Build
  - [x] Splash & progress bar
  - [x] Download online resource and copy to Resource folder when build.
  - [x] C++ change icon on executable.
    - https://www.codeproject.com/Articles/30644/Replacing-ICON-resources-in-EXE-and-DLL-files
https://www.codeproject.com/Questions/634767/c-cplusplus-change-icon-on-executable-please-help
  - [ ] Move to project configure tab
- [ ] TextAssetMap
  - [ ] ~~UI rebuild. Can view all asset in update process test.~~
  - [ ] ~~Download resource seperately when preview.~~
  - [x] Bug: TextAssetMapOptionProperties does not responce when copied and pasted
    - http://karlhulme.wordpress.com/2007/02/15/masking-input-to-a-wpf-textbox/
  - [ ] GetHashCode
    - https://stackoverflow.com/questions/26019285/binding-selecteditem-vs-selectedindex-when-should-i-choose-one-over-the-other
    - https://stackoverflow.com/questions/32837485/overriding-gethash-code-and-equals-break-bindings
      - https://blogs.msdn.microsoft.com/ericlippert/2011/02/28/guidelines-and-rules-for-gethashcode/
    - [ ] ~~Filter to find sentense.~~
- [ ] Project & Patcher Json
  - project json save all changes
    - [ ] OnlineUpdate: save all parameter(not only selected)
- [ ] AssetMapOptionsProperties
  - [ ] Button that clear all AssetMapOptions
- [x] TextAssetPlugin.
  - [x] gettext catalog (.po file).
  - [x] Regexp.
    - http://www.sapphosound.com/archives/1653
- [ ] Online resource updater.
  - [x] Saved in temp folder.
  - [x] Saved in Resource folder when build.
    - Bug fix: download at Project\Resource to at Project\Build\Resource
  - [x] Download resouece when textassetTest

  - [x] Struct only contain file name and URL.
  - [x] Implement in C# and async work.
  - [ ] ~~Automatically listing from TextAssetMap.~~
  - http://www.cplusplus.com/forum/windows/53113/
    - https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775123(v=vs.85)
- [ ] ~~MonoTextAssetPlugin~~
  - [x] Removed from InteractWithTextAsset and InteractWithFileText.
  - [ ] ~~Implement with seperating with TextAssetPlugin~~
  - [ ] ~~i2 Localization(I2.Loc.LanguageSource).~~
- [ ] ~~FontAssetPlugin.~~
  - [ ] ~~tk2d(FontGroup, see Bomber Crew sample).~~
  - [ ] ~~Font asset.~~
- [x] Project configure tab.
  - [x] Patch notice.
    - Set version information.
    - Detect from currentVersion.txt file.
    - [x] Self-Patch for binary, configure.
      - [x] Use splash during check lastest release.
        - https://stackoverflow.com/questions/31164067/wpf-splashscreen-using-external-image
        - Prograss bar, splash image, "Check lastest version".
        - Update yes, no dialog
        - UpdateFunction and return result successfully updated. then run updated program and exit self as a result.
      - https://stackoverflow.com/questions/9162969/how-can-a-c-binary-replace-itself
      - GitHub release API https://developer.github.com/v3/repos/releases/
      - C++ response GET https://stackoverflow.com/questions/38885184/get-the-http-response-for-a-url-in-c
      - OnceClick  http://namocom.tistory.com/m/385?category=503608
- [x] Patcher interface.
  - Single page.
  - [x] Image from external
    - [x] Default image.
    - https://social.msdn.microsoft.com/Forums/vstudio/en-US/74f716a1-073f-40c5-a488-c05b42f6067e/how-to-access-external-images-in-wpf-via-c-code?forum=wpf
  - [ ] ~~i18n & L10n~~
    - http://kojaedoo.tistory.com/m/648
    - https://developerfeel.blogspot.com/2014/07/wpf-globalization-language-using.html?m=1
    - (Advanced) https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-globalization-and-localization-overview
- [ ] ~~Handle AssetBundle.~~
- [x] ~~Use jsoncpp dll.~~ Un-use stdAfx.h
  - ~~Build with Meson/Ninja~~
- [ ] ~~Optimization~~
  - [ ] ~~change from not to search all TextAsset(GetTextAssetMaps) to implemenet GetTranslatedMaps.~~
